name: Build and Publish

# TODO: Add description

on:
  workflow_dispatch:

jobs:  
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_PLAYGROUND_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PLAYGROUND_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker image
        run: |
          docker build -t 755521597925.dkr.ecr.us-east-1.amazonaws.com/playground/ai-coding-agent:${{ github.run_id }} -f Dockerfile .

      - name: Push Docker image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 755521597925.dkr.ecr.us-east-1.amazonaws.com
          docker push 755521597925.dkr.ecr.us-east-1.amazonaws.com/playground/ai-coding-agent:${{ github.run_id }}

  # slackNotificationSuccess:
  #   name: Slack Notification (Success)
  #   runs-on: ubuntu-latest
  #   needs: build-and-publish
  #   if: needs.build-and-publish.result == 'success'
  #   steps:
  #     - name: Send Success Notification
  #       uses: slackapi/slack-github-action@v2.1.0
  #       with:
  #         webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         webhook-type: incoming-webhook
  #         payload: |
  #           blocks:
  #             - type: "section"
  #               text:
  #                 type: "mrkdwn"
  #                 text: "<${{ github.server_url }}/${{ github.repository }}|${{ inputs.service_name }}> *${{ inputs.environment }}* new image has been published :white_check_mark:"
  #             - type: "section"
  #               text:
  #                 type: "mrkdwn"
  #                 text: "Image has been published to ${{ vars.DOCKER_CONTAINER_REGISTRY_HOST }}/${{ inputs.service_name }}:${{ inputs.image_tag }}"
  #             - type: "section"
  #               text:
  #                 type: "mrkdwn"
  #                 text: "> Check the logs for <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|details>."

  # slackNotificationFailure:
  #   name: Slack Notification (Failure)
  #   runs-on: ubuntu-latest
  #   needs: build-and-publish
  #   if: always() && needs.build-and-publish.result == 'failure'
  #   steps:
  #     - name: Send Failure Notification
  #       uses: slackapi/slack-github-action@v2.1.0
  #       with:
  #         webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         webhook-type: incoming-webhook
  #         payload: |
  #           blocks:
  #             - type: "section"
  #               text:
  #                 type: "mrkdwn"
  #                 text: "<${{ github.server_url }}/${{ github.repository }}|${{ inputs.service_name }}> *${{ inputs.environment }}* image creation failed :x:"
  #             - type: "section"
  #               text:
  #                 type: "mrkdwn"
  #                 text: "Image ${{ inputs.service_name }}:${{ inputs.image_tag }} to be published"
  #             - type: "section"
  #               text:
  #                 type: "mrkdwn"
  #                 text: "> Check the logs for <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|details>."
