name: Create/Update infrastructure

on:
  workflow_dispatch:
    inputs:
      tf_vars_files:
        description: "Used in the terraform command, format: -var-file=var-file-1.tfvars -var-file=var-file-2.tfvars"
        type: string
        required: true

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_AI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_AI }}
          aws-region: ${{ env.AWS_REGION }}
      
      - run: terraform init

      - id: plan
        run: terraform plan -no-color ${{ inputs.tf_vars_files }}

      - name: Terraform Apply
        run: terraform apply -auto-approve ${{ inputs.tf_vars_files }}
