name: Manual Production Deployment

env:
  ECR_URL: 767397775295.dkr.ecr.us-east-2.amazonaws.com
  ECR_PATH: /ai/ai-coding-agent
  AWS_REGION: us-east-2

on:
  workflow_dispatch:
    inputs:
      image_tag:
        type: string
        description: "Image tag to be deployed"
        required: true

jobs:
  update-infrastructure:
    uses: ./.github/workflows/infrastructure.yml
    with:
      tf_vars_files: "-var-file=var_files/ai.tfvars.safe"
      image_tag: ${{ inputs.image_tag }}
      domain_name: "bit"
      environment_tag: production
      s3_key: "terraform/production.tfstate"
    secrets: inherit
  
  update-ecr-tracking:
    runs-on: ubuntu-latest
    needs:
      - update-infrastructure
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_AI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_AI }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Push Docker image
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL
          docker pull $ECR_URL$ECR_PATH:${{ inputs.image_tag }}
          docker tag $ECR_URL$ECR_PATH:${{ inputs.image_tag }} $ECR_URL$ECR_PATH:production
          docker push $ECR_URL$ECR_PATH:production
