name: Manual Staging Deployment

on:
  workflow_dispatch:
    inputs:
      image_tag:
        type: string
        description: "Image tag to be deployed"
        required: true

jobs:
  update-infrastructure:
    uses: ./.github/workflows/infrastructure.yml
    with:
      tf_vars_files: "-var-file=var_files/ai.tfvars.safe"
      image_tag: ${{ inputs.image_tag }}
      domain_name: "bit-staging"
      environment_tag: staging
      s3_key: "terraform/staging.tfstate"
      enable_execute_command: true
    secrets: inherit

