name: Production

on:
  workflow_dispatch:
  release:
    types: [published, created, edited]

jobs:
  get-last-successful-staging-run-id:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.last_successful_build.outputs.run-id }}
    steps:
      - name: Find last successful build
        uses: SamhammerAG/last-successful-build-action@v7.2
        with:
          branch: 'main'
          workflow: 'Staging'
        id: last_successful_build

  update-infrastructure:
    uses: ./.github/workflows/infrastructure.yml
    needs:
      - get-last-successful-staging-run-id
    with:
      tf_vars_files: "-var-file=var_files/ai.tfvars.safe"
      image_tag: ${{ needs.get-last-successful-staging-run-id.outputs.run_id }}
      domain_name: "bit"
      environment_tag: production
    secrets: inherit
