name: Staging

on:
  workflow_dispatch:
  push:
    branch:
      - main

jobs:
  build-and-publish:
    uses: ./.github/workflows/build_and_publish.yml
    with:
      image_tag: ${{ github.run_id }}
      environment_tag: staging
    secrets: inherit
